name: build-on-push
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: setup msbuild
        uses: microsoft/setup-msbuild@v2
      - name: build debug
        run:  msbuild msvc2022\util.sln -t:rebuild -verbosity:quiet -property:Configuration=debug
      - name: build release
        run:  msbuild msvc2022\util.sln -t:rebuild -verbosity:quiet -property:Configuration=release
      - name: short sha
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)"  >> $GITHUB_OUTPUT
      - name: check short sha
        run: |
            echo "sha_short: $env:sha_short"
        env:
          sha_short: ${{ steps.vars.outputs.sha_short }}
      - name: run debug tests
        run:  bin\debug\test1.exe --verbosity quiet
      - name: run release tests
        run:  bin\release\test1.exe --verbosity quiet
      - name: upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: xrt.release.zip
          path: |
            bin\release\test1.exe
          retention-days: 5
      - name: upload debug artifact
        uses: actions/upload-artifact@v4
        with:
          name: xrt.debug.zip
          path: |
            bin\debug\test1.exe
          retention-days: 5