name: build-on-push
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    permissions:
      id-token: write
      contents: read
      attestations: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive            
      - name: setup msbuild
        uses: microsoft/setup-msbuild@v2
      - name: build debug
        run:  msbuild msvc2022\ui.sln -t:rebuild -verbosity:quiet -property:Configuration=debug
      - name: build release
        run:  msbuild msvc2022\ui.sln -t:rebuild -verbosity:quiet -property:Configuration=release
      - name: short sha
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)"  >> $GITHUB_OUTPUT
      - name: check short sha
        run: |
            echo "sha_short: $env:sha_short"
        env:
          sha_short: ${{ steps.vars.outputs.sha_short }}
      - name: run debug tests
        run:  bin\debug\test1.exe --verbosity quiet
      - name: run release tests
        run:  bin\release\test1.exe --verbosity quiet
      - name: Attest Build Provenance
        uses: actions/attest-build-provenance@v1.1.2
        with:
          subject-path: 'bin\**\*.exe'
      - name: upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: ui.release.zip
          path: |
            bin\release\test1.exe
            bin\release\test2.exe
            bin\release\sample1.exe
            bin\release\sample2.exe
            bin\release\sample3.exe
            bin\release\sample4.exe
            bin\release\sample5.exe
            bin\release\sample6.exe
            bin\release\sample9.exe
          retention-days: 5
      - name: upload debug artifact
        uses: actions/upload-artifact@v4
        with:
          name: ui.debug.zip
          path: |
            bin\debug\test1.exe
            bin\debug\test2.exe
            bin\debug\sample1.exe
            bin\debug\sample2.exe
            bin\debug\sample3.exe
            bin\debug\sample4.exe
            bin\debug\sample5.exe
            bin\debug\sample6.exe
            bin\debug\sample9.exe
          retention-days: 5
          